=head1 NAME

MojoX::Util::ResponseFilter - ResponseFilter in Plack::Middleware style [EXPERIMENTAL]

=head1 SYNOPSIS

    sub startup {
        ....

        use MojoX::Util::ResponseFilter 'enable';
        enable($self, [
            'Plack::Middleware::Some',
            'Plack::Middleware::Some2' => \@args,
        ]);
        
        enable_if($self,
            sub {...}, [
                'Plack::Middleware::Some',
                'Plack::Middleware::Some2' => \@args,
            ]
        );
        
    }
    
    package Plack::Middleware::Some;
    use strict;
    use warnings;
    use base qw( Plack::Middleware );
    
    sub call {
        
        my $self = shift;
        my $res = $self->app->(@_);
        $self->response_cb($res, sub {
            my $res = shift;
            my $h = Plack::Util::headers($res->[1]);
            if ($h->get('Content-Type') =~ 'text/html') {
                return sub {
                    my $chunk = shift;
                    
                    ### DO SOMETHING
                    
                    return $chunk;
                };
            }
            $res;
        });
    }

=head1 DESCRIPTION

MojoX::Util::ResponseFilter allows you to activate Plack::Middleware style body
filters on after_dispatch hook.

=head1 METHODS

=head2 MojoX::Util::ResponseFilter::enable($mojo_app, $args_array_ref)

Sets Plack::Middleware::* to after_dispatch hook of mojo app as a callback.

    MojoX::Util::ResponseFilter->enable($mojo_app, ['some::mw1','some::mw2'])

Middleware arguments can be set in array refs following to package name.

    MojoX::Util::ResponseFilter->enable($mojo_app, [
        'some::mw1' => [$args1, $args2],
        'some::mw2' => [$args1, $args2],
    ])

=head2 MojoX::Util::ResponseFilter::enable_if($mojo_app, $cb, $args_array_ref)

enable_if is also available

    enable_if($self,
        sub {
            my $mojo_controller = shift;
            if (...) {
                return 1;
            }
        }, [
            'TestFilter',
        ]
    );

=head1 METHOD

=head2 enable($mojo_app, $middlewares)

=head2 enable_if($mojo_app, $condition, $middlewares)

if $condition is true, $middleware would be activate.

=head1 AUTHOR

Sugama Keita, E<lt>sugama@jamadam.comE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2011 by Sugama Keita.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
