=head1 NAME

MojoX::Util::PlackMiddleware - Response Filter in Plack::Middleware style

=head1 SYNOPSIS

    sub startup {
        ....
        
        my $self = shift;
        
        $self->plugin('plack_middleware', [
            'Plack::Middleware::Some1', 
            'Plack::Middleware::Some2', {arg1 => 'some_vale'}
        ]);
        $self->plugin('plack_middleware', [
            'Plack::Middleware::Some1', sub {$condition}, 
            'Plack::Middleware::Some2', sub {$condition}, {arg1 => 'some_vale'}
        ]);
    }
    
    package Plack::Middleware::Some;
    use strict;
    use warnings;
    use base qw( Plack::Middleware );
    
    sub call {
        
        my ($self, $env) = @_;
        $self->response_cb($self->app->($env), sub {
            my $res = shift;
            
            ### DO SOMETHING
            
            $res;
        });
    }

=head1 DESCRIPTION

Mojolicious::Plugin::PlackMiddleware allows you to activate Plack::Middleware
style body filters on after_dispatch hook.

=head1 METHODS

=head2 register

=head1 AUTHOR

Sugama Keita, E<lt>sugama@jamadam.comE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2011 by Sugama Keita.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
